#python progrrame
id=int(input('Enetr your Id: '))
urname=input('Enter your name:  ' )
clas=input('Enetr your class:  ')
Branch=input("Enetr yor branch:  ")
clgname=input("Enter your college name:  ")
exam=input('Enter your last qualified exam:  ')
gender=input('Eneter your gender:  ')
age=int(input('Enetr your  age:  ' ))
contact=input('Enetr your contact:  ')
emailid=input('Enetr your email:  ')
print('You are registered!!!!!!!!!')